import type { jsPDF } from "jspdf";
import { fetchWorkspaceSettings } from "./workspaceSettings";

/**
 * The brand, as a printed document.
 *
 * ActiveApps is a dark-navy interface everywhere except here: the brand's own
 * rule is that print collateral is the light variant — navy "ACTIVE", mint
 * "APPS", white page. So these are not the app's CSS tokens transplanted; they
 * are the same brand expressed for ink.
 *
 * Both PDF generators draw from this module. They used to carry ~60 lines of
 * byte-identical drawing code each, which is how the two documents a client
 * receives in one email drifted apart in the first place.
 */

export type RGB = [number, number, number];

/* ---------- Print palette ----------
   Mint is a FILL colour on white, not a text colour. Measured against white:
   #3CC998 is 2.09:1, which fails even the 3:1 large-text bar; #32A67D reaches
   3.05:1 and is therefore allowed only at >=12pt bold. Navy on mint is 8.98:1,
   which is why the mint total row carries navy text. */
export const INK: RGB = [12, 18, 26]; // #0C121A  --navy
export const INK_SOFT: RGB = [77, 85, 95]; // #4D555F  table body
export const INK_FAINT: RGB = [138, 144, 153]; // #8A9099  labels, captions
export const RULE: RGB = [225, 228, 232]; // #E1E4E8  hairlines
export const SURFACE: RGB = [244, 246, 248]; // #F4F6F8  tiles, zebra
export const MINT: RGB = [60, 201, 152]; // #3CC998  --mint
export const MINT_DEEP: RGB = [50, 166, 125]; // #32A67D  --mint-dim
export const PAPER: RGB = [255, 255, 255];

/** A4 at 72dpi, and the one margin every element aligns to. */
export const MARGIN = 40;
/** --radius-md, in points. */
export const RADIUS = 6;

/** The brand's mono face, or the fallback when it could not be loaded. */
export type MonoFont = string;

/* ---------- Colour helpers ---------- */

export function hexToRgb(hex: string): RGB | null {
  const m = /^#?([0-9a-f]{6})$/i.exec(hex.trim());
  if (!m) return null;
  const n = parseInt(m[1], 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
}

/**
 * Ink that stays readable on a filled block. The accent is configurable, so a
 * dark custom accent would otherwise get navy text on navy fill.
 */
export function onAccent(fill: RGB): RGB {
  const lin = (c: number) => {
    const s = c / 255;
    return s <= 0.03928 ? s / 12.92 : ((s + 0.055) / 1.055) ** 2.4;
  };
  const l = 0.2126 * lin(fill[0]) + 0.7152 * lin(fill[1]) + 0.0722 * lin(fill[2]);
  return l > 0.35 ? INK : PAPER;
}

/* ---------- Workspace-configurable bits ---------- */

export interface BrandSettings {
  accent: RGB;
  footerText: string;
}

/**
 * Read here rather than threaded through every caller's options:
 * fetchWorkspaceSettings is already module-cached, and this is what finally
 * makes `pdfAccentColor` — written by the settings page since Phase 3 and read
 * by nothing at all — actually reach a document.
 */
export async function brandSettings(): Promise<BrandSettings> {
  try {
    const s = await fetchWorkspaceSettings();
    return {
      accent: hexToRgb(s.pdfAccentColor) ?? MINT,
      footerText: s.pdfFooterText?.trim() || "Generated by ActiveApps CRM",
    };
  } catch {
    return { accent: MINT, footerText: "Generated by ActiveApps CRM" };
  }
}

/* ---------- Logo ---------- */

let logoPromise: Promise<string | null> | null = null;

/**
 * The wordmark logo as a data URL, downscaled to 128px first.
 *
 * The source is 1201x1201 and gets drawn at 30pt — roughly 2900 DPI, and the
 * bulk of a finished PDF's weight, because jsPDF embeds whatever pixels it is
 * handed. 128px at 30pt is ~307 DPI, which is past what any printer resolves.
 * Doing it at runtime rather than shipping a second asset means it stays right
 * if the logo is ever replaced.
 */
export function loadLogoDataUrl(): Promise<string | null> {
  if (!logoPromise) logoPromise = fetchAndShrinkLogo();
  return logoPromise;
}

const LOGO_PX = 128;

async function fetchAndShrinkLogo(): Promise<string | null> {
  try {
    const res = await fetch("/aa-logo.png");
    if (!res.ok) return null;
    const blob = await res.blob();
    const raw = await new Promise<string | null>((resolve) => {
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result as string);
      reader.onerror = () => resolve(null);
      reader.readAsDataURL(blob);
    });
    if (!raw) return null;
    return (await shrink(raw)) ?? raw;
  } catch {
    return null;
  }
}

async function shrink(dataUrl: string): Promise<string | null> {
  try {
    const img = await new Promise<HTMLImageElement>((resolve, reject) => {
      const el = new Image();
      el.onload = () => resolve(el);
      el.onerror = reject;
      el.src = dataUrl;
    });
    if (!img.width || !img.height) return null;
    if (img.width <= LOGO_PX && img.height <= LOGO_PX) return dataUrl;
    const canvas = document.createElement("canvas");
    canvas.width = LOGO_PX;
    canvas.height = LOGO_PX;
    const ctx = canvas.getContext("2d");
    if (!ctx) return null;
    // Fit inside the square and centre, so a future non-square mark is not
    // stretched the way a straight draw would stretch it.
    const scale = LOGO_PX / Math.max(img.width, img.height);
    const w = img.width * scale;
    const h = img.height * scale;
    ctx.drawImage(img, (LOGO_PX - w) / 2, (LOGO_PX - h) / 2, w, h);
    return canvas.toDataURL("image/png");
  } catch {
    return null;
  }
}

/* ---------- Mono face ---------- */

const MONO_FAMILY = "JetBrainsMono";
const MONO_FILES = [
  { file: "JetBrainsMono-Regular.ttf", style: "normal" },
  { file: "JetBrainsMono-Bold.ttf", style: "bold" },
] as const;

let monoPromise: Promise<{ file: string; style: string; b64: string }[] | null> | null =
  null;

/**
 * Register the brand's mono face on this document and return the family name
 * to pass to setFont — or "courier" if it could not be loaded.
 *
 * A missing font must never cost someone their export, so every failure path
 * degrades to a built-in face rather than throwing. The bytes are fetched once
 * per session; the VFS registration is per document, because jsPDF's virtual
 * file system belongs to the instance.
 */
export async function registerMono(doc: jsPDF): Promise<MonoFont> {
  if (!monoPromise) monoPromise = fetchMono();
  const files = await monoPromise;
  if (!files) return "courier";
  try {
    for (const f of files) {
      doc.addFileToVFS(f.file, f.b64);
      doc.addFont(f.file, MONO_FAMILY, f.style);
    }
    return MONO_FAMILY;
  } catch {
    return "courier";
  }
}

async function fetchMono() {
  try {
    return await Promise.all(
      MONO_FILES.map(async (f) => {
        const res = await fetch(`/fonts/${f.file}`);
        if (!res.ok) throw new Error(String(res.status));
        const bytes = new Uint8Array(await res.arrayBuffer());
        // A TrueType file opens with 0x00010000. Checking matters because a
        // missing path under an SPA fallback answers 200 with index.html, and
        // jsPDF's parser would then fail somewhere far less obvious.
        if (!(bytes[0] === 0 && bytes[1] === 1 && bytes[2] === 0 && bytes[3] === 0)) {
          throw new Error("not a TrueType file");
        }
        return { file: f.file, style: f.style as string, b64: bytesToBase64(bytes) };
      }),
    );
  } catch {
    return null;
  }
}

/**
 * Chunked on purpose: String.fromCharCode(...bytes) blows the call stack once
 * the input passes ~100 KB, which a PDF easily does.
 */
export function bytesToBase64(bytes: Uint8Array): string {
  let binary = "";
  const CHUNK = 0x8000;
  for (let i = 0; i < bytes.length; i += CHUNK) {
    binary += String.fromCharCode(...bytes.subarray(i, i + CHUNK));
  }
  return btoa(binary);
}

/* ---------- Type ---------- */

/** The brand's label treatment: mono, uppercase, 0.15em tracking. */
export function drawLabel(
  doc: jsPDF,
  text: string,
  x: number,
  y: number,
  opts: {
    mono: MonoFont;
    size?: number;
    color?: RGB;
    bold?: boolean;
    align?: "left" | "right";
    /** Off for values — a document number is data, not a label to shout. */
    uppercase?: boolean;
    /**
     * Letter-spacing as a multiple of the size; the brand's label spec is
     * 0.15em. Worth turning down for anything a reader might copy out: PDF
     * extractors read wide tracking as word breaks, so "KODEM SECURITY" comes
     * back as "K O D E M". Decorative labels can afford that; data cannot.
     */
    track?: number;
  },
): number {
  const size = opts.size ?? 6.5;
  const track = size * (opts.track ?? 0.15);
  const upper = opts.uppercase === false ? text : text.toUpperCase();
  doc.setFont(opts.mono, opts.bold === false ? "normal" : "bold");
  doc.setFontSize(size);
  doc.setTextColor(...(opts.color ?? INK_FAINT));
  // Width is measured before the tracking is applied and corrected by hand:
  // jsPDF's align option does not account for charSpace, so a right-aligned
  // tracked label would drift further right the longer it got.
  const width = doc.getTextWidth(upper) + track * Math.max(0, upper.length - 1);
  const startX = opts.align === "right" ? x - width : x;
  doc.setCharSpace(track);
  doc.text(upper, startX, y);
  doc.setCharSpace(0);
  return width;
}

/* ---------- Blocks ---------- */

/**
 * Logo, ACTIVEAPPS wordmark and tagline. Returns the y of the block's baseline
 * so callers can flow beneath it instead of guessing another magic number.
 */
export async function drawWordmark(
  doc: jsPDF,
  mono: MonoFont,
  x: number,
  top: number,
): Promise<number> {
  const logo = await loadLogoDataUrl();
  if (logo) {
    try {
      // "FAST" matters more than it looks: with no compression flag jsPDF
      // stores the decoded logo raw and the file balloons — fine for a local
      // download, rude as an email attachment.
      doc.addImage(logo, "PNG", x, top, 30, 30, undefined, "FAST");
    } catch {
      /* the mark is optional; the wordmark still identifies the document */
    }
  }
  const textX = logo ? x + 40 : x;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.setTextColor(...INK);
  doc.text("ACTIVE", textX, top + 16);
  const activeW = doc.getTextWidth("ACTIVE");
  // Mint stays on "APPS" even on white: the brand specifies exactly this for
  // print, and at 15pt bold it is display type rather than reading text.
  doc.setTextColor(...MINT);
  doc.text("APPS", textX + activeW, top + 16);
  drawLabel(doc, "Tech Orchestration", textX, top + 28, {
    mono,
    size: 6.5,
    color: INK_FAINT,
    bold: false,
  });
  return top + 30;
}

/** Full-width hairline. The accent one is the brand's rule under a header. */
export function drawRule(
  doc: jsPDF,
  x: number,
  y: number,
  width: number,
  color: RGB = RULE,
  thickness = 0.5,
) {
  doc.setDrawColor(...color);
  doc.setLineWidth(thickness);
  doc.line(x, y, x + width, y);
}

/**
 * The brand's section divider — a rotated square in the accent — followed by
 * the section title, with optional right-aligned mono meta.
 */
export function drawSectionHeading(
  doc: jsPDF,
  mono: MonoFont,
  x: number,
  y: number,
  width: number,
  title: string,
  opts: { accent: RGB; meta?: string },
): number {
  const r = 2.6;
  doc.setDrawColor(...opts.accent);
  doc.setLineWidth(1);
  doc.lines([[r, -r], [r, r], [-r, r]], x, y - 3, [1, 1], "S", true);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...INK);
  doc.text(title, x + r * 2 + 7, y);

  if (opts.meta) {
    drawLabel(doc, opts.meta, x + width, y, {
      mono,
      size: 7.5,
      color: INK_FAINT,
      align: "right",
    });
  }
  return y + 8;
}

export interface StatTile {
  label: string;
  value: string;
  /** Marks the one figure the document is really about. */
  accented?: boolean;
}

/** Evenly-spaced stat tiles across the content width. */
export function drawStatTiles(
  doc: jsPDF,
  mono: MonoFont,
  x: number,
  y: number,
  width: number,
  tiles: StatTile[],
  accent: RGB,
): number {
  const gap = 10;
  const height = 46;
  const tileW = (width - gap * (tiles.length - 1)) / tiles.length;
  tiles.forEach((t, i) => {
    const tx = x + i * (tileW + gap);
    doc.setFillColor(...SURFACE);
    doc.setDrawColor(...RULE);
    doc.setLineWidth(0.5);
    doc.roundedRect(tx, y, tileW, height, RADIUS, RADIUS, "FD");
    if (t.accented) {
      // A cap-rule rather than a filled tile: one accent, not three.
      doc.setDrawColor(...accent);
      doc.setLineWidth(2);
      doc.line(tx + RADIUS, y + 1, tx + tileW - RADIUS, y + 1);
    }
    drawLabel(doc, t.label, tx + 10, y + 17, { mono, size: 6.5, color: INK_FAINT });
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(...INK);
    doc.text(t.value, tx + 10, y + 36);
  });
  return y + height;
}

/**
 * Footer on every page. Page numbers are opt-in because a one-page invoice
 * saying "Page 1 of 1" is noise, while a six-page breakdown needs them.
 */
export function drawFooter(
  doc: jsPDF,
  mono: MonoFont,
  opts: { footerText: string; pageNumbers?: boolean },
) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const count = doc.getNumberOfPages();
  for (let i = 1; i <= count; i++) {
    doc.setPage(i);
    const y = pageHeight - 26;
    drawRule(doc, MARGIN, y - 12, pageWidth - MARGIN * 2);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(...INK_FAINT);
    doc.text(opts.footerText, MARGIN, y);
    const right = opts.pageNumbers
      ? `activeapps.io  ·  Page ${i} of ${count}`
      : "activeapps.io";
    drawLabel(doc, right, pageWidth - MARGIN, y, {
      mono,
      size: 6.5,
      color: INK_FAINT,
      bold: false,
      align: "right",
    });
  }
}

/* ---------- Tables ---------- */

/**
 * The shared table look: no cell grid, zebra rows, a mono head on navy.
 * `muted` renders a table that is visibly not being charged for — used by the
 * internal-hours section, where a navy head and mint totals would read as a
 * bill.
 */
export function tableTheme(mono: MonoFont, opts?: { muted?: boolean }) {
  const muted = !!opts?.muted;
  return {
    theme: "plain" as const,
    styles: {
      font: "helvetica",
      fontSize: 8.5,
      cellPadding: { top: 5, right: 6, bottom: 5, left: 6 },
      textColor: (muted ? INK_FAINT : INK_SOFT) as RGB,
      lineColor: RULE as RGB,
      lineWidth: 0,
      overflow: "linebreak" as const,
    },
    headStyles: {
      font: mono,
      fontStyle: "bold" as const,
      fontSize: 7,
      fillColor: (muted ? SURFACE : INK) as RGB,
      textColor: (muted ? INK_FAINT : PAPER) as RGB,
      cellPadding: { top: 6, right: 6, bottom: 6, left: 6 },
    },
    alternateRowStyles: { fillColor: (muted ? PAPER : SURFACE) as RGB },
  };
}

/** autoTable stores its end position on the instance rather than returning it. */
export function tableEnd(doc: jsPDF, fallback: number): number {
  return (
    (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable
      ?.finalY ?? fallback
  );
}
